#! /usr/bin/env bash

print_title () 
{
    printf '\n%.0s' {1..2};
    printf '=%.0s' {1..51};
    printf "\n/. 🚀 $1\n"
    printf '=%.0s' {1..51};
    printf '\n%.0s' {1..2};
}

function filter 
{
    local parent=`echo $1 | sed -n 's/[^/\]\+$//p'`
    echo $1
    while read it
    do
        if [[ -z "$it" ]]; then break; fi
        doc="$parent${it/.rst/}.rst"
        if ( [ -a $doc ] || [ -a "$doc.rst" ] ) && [ -z ${doc/*index.rst/} ]
        then
            echo "➊==>$doc" >&2
            filter "$doc"
        else
            echo "➋$doc" >&2
            echo "$doc"
        fi
    done <<< $( sed -n "/^.. toctree::/,/^\S/{ s/^ \+[^:]\+$/\0/p }" $1 \
      | sed -n 's|.*<\(.*\)>|\1|;p' \
      )
}

function include()
{
    while read -r it
    do 
        if [[ -z "$it" ]]; then break; fi
        echo "➌+++$1" >&2
        print_title "$it"
        printf ".. code-block:: \n\n"
        cat $it | sed -n 's/.*/    \0/p'
    done <<< $(cat "$1" | sed -n 's/.. include:://p')
}

function toc() 
{
    # echo ../README.md
    filter ./index.rst
}

function doc()
{
    cat << EOF
文档合并脚本中使用了 sed 流式编辑器、awk 结构化数据编辑器，使用教程参考 OpenDocs： 

1. [Sed in 5 Minutes](https://github.com/Jeangowhy/opendocs/blob/main/sed.info)
2. [AWK in 5 Minutes](https://github.com/Jeangowhy/opendocs/blob/main/sed.info)

EOF
}

function self_include()
{
    print_title "Docs combine script"
    doc
    echo '.. code-block:: bash'

    echo ''
    cat "$0" | sed -n 's/^/    /p'

    echo ''
    echo "Docs files count: `find ./ -name "*.rst" | wc -l` ::"
    echo ''
    find ./ -name "*.rst" | sed -n 's/.*/    \0/p' | grep -v library
}

function combine() 
{
    self_include
    while read -r it
    do 
        print_title "$it"
        cat "$it"
        include "$it"
    done << EOF
`toc`
EOF
}


out=/c/opendocs/haskell_docs.rst
combine > $out
subl $out
