:source-highlighter: highlight.js

pass:[<style>
.imageblock.right {
    max-width: 320px;position:absolute;z-index:2;right:42px;
    }
.imageblock.right:hover {
    opacity:0.2;
    }
    </style>]

TIP: https://www.ctan.org/pkg/tkz-euclide[tkz-euclide - Tools for drawing Euclidean geometry]

== \part{General survey : a brief but comprehensive review}

=== \input{TKZdoc-euclide-presentation.tex}

.tkzexample 001 Presentation and Overview
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_001]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=docstyle]

include::TKZdoc-euclide-src.adoc[tag=ex_001]
----
****


.tkzexample 002 Complete code with tkz-euclide
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_002]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_002]
----
****


.tkzexample 003 Book I, Proposition II Euclid's Elements
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_003]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_003]
----
****


.tkzexample 004 Let's look at a classic example
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_004]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_004]
----
****


.tkzexample 005 Part I: golden triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_005]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_005]
----
****


.tkzexample 006 Part II: two others methods with golden and euclid triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_006]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_006]
----
****


.tkzexample 007 Part II: two others methods with golden and euclid triangle 2
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_007]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_007]
----
****


.tkzexample 008 Complete but minimal example
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_008]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_008]
----
****


=== \input{TKZdoc-euclide-elements.tex}

.tkzexample 009 Objects and language
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_009]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_009]
----
****


.tkzexample 010 Notations and conventions
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_010]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_010]
----
****


.tkzexample 011 Notations and conventions 2
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_011]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_011]
----
****


.tkzexample 012 Notations and conventions 3
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_012]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_012]
----
****


== \part{Setting}

=== \input{TKZdoc-euclide-points.tex}

.tkzexample 013 Definition of a point : tkzDefPoint or tkzDefPoints
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_013]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_013]
----
****


.tkzexample 014 Definition of a point : tkzDefPoint or tkzDefPoints 2
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_014]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_014]
----
****


.tkzexample 015 Cartesian coordinates
****
[tikz,role=right,width=120]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_015]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_015]
----
****


.tkzexample 016 Calculations with xfp
****
[tikz,role=right,width=120]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_016]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_016]
----
****


.tkzexample 017 Polar coordinates
****
[tikz,role=right,width=120]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_017]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_017]
----
****


.tkzexample 018 Relative points
****
[tikz,role=right,width=120]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_018]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_018]
----
****


.tkzexample 019 Isosceles triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_019]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_019]
----
****


.tkzexample 020 Equilateral triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_020]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_020]
----
****


.tkzexample 021 Parallelogram
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_021]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_021]
----
****


.tkzexample 022 Create a triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_022]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_022]
----
****


.tkzexample 023 Create a square
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_023]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_023]
----
****


== \part{Calculating}

=== \input{TKZdoc-euclide-pointsSpc.tex}

.tkzexample 024 Use of tkzDefMidPoint
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_024]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_024]
----
****


.tkzexample 025 Use the golden ratio to divide a line segment
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_025]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_025]
----
****


.tkzexample 026 Golden arbelos
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_026]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_026]
----
****


.tkzexample 027 with two points
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_027]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_027]
----
****


.tkzexample 028 with three points
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_028]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_028]
----
****


.tkzexample 029 Internal and external with node
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_029]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_029]
----
****


.tkzexample 030 D'Alembert Theorem
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_030]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_030]
----
****


.tkzexample 031 Example with node
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_031]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_031]
----
****


.tkzexample 032 options ext and int
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_032]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_032]
----
****


.tkzexample 033 Bisector and harmonic division
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_033]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_033]
----
****


.tkzexample 034 option both
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_034]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_034]
----
****


.tkzexample 035 Using tkzDefEquiPoints with options
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_035]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_035]
----
****


.tkzexample 036 Middle of an arc
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_036]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_036]
----
****


.tkzexample 037 Use of option pos
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_037]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_037]
----
****


.tkzexample 038 Altshiller's Theorem
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_038]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_038]
----
****


.tkzexample 039 Use of tkzDefPointOnCircle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_039]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_039]
----
****


.tkzexample 040 Option ortho or orthic
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_040]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_040]
----
****


.tkzexample 041 Option centroid
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_041]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_041]
----
****


.tkzexample 042 Option circum
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_042]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_042]
----
****


.tkzexample 043 Option in
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_043]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_043]
----
****


.tkzexample 044 Option ex
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_044]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_044]
----
****


.tkzexample 045 Option euler
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_045]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_045]
----
****


.tkzexample 046 Option symmedian
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_046]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_046]
----
****


.tkzexample 047 Option spieker
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_047]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_047]
----
****


.tkzexample 048 Option gergonne
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_048]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_048]
----
****


.tkzexample 049 Option nagel
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_049]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_049]
----
****


.tkzexample 050 Option  mittenpunkt
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_050]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_050]
----
****


.tkzexample 051 Relation between gergonne, centroid and mittenpunkt
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_051]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_051]
----
****


=== \input{TKZdoc-euclide-pointby.tex}

.tkzexample 052 translation
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_052]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_052]
----
****


.tkzexample 053 reflection (orthogonal symmetry)
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_053]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_053]
----
****


.tkzexample 054 homothety and projection
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_054]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_054]
----
****


.tkzexample 055 projection
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_055]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_055]
----
****


.tkzexample 056 symmetry
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_056]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_056]
----
****


.tkzexample 057 rotation 
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_057]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_057]
----
****


.tkzexample 058 rotation in radian
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_058]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_058]
----
****


.tkzexample 059 rotation with nodes
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_059]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_059]
----
****


.tkzexample 060 inversion
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_060]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_060]
----
****


.tkzexample 061 inversion 2
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_061]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_061]
----
****


.tkzexample 062 Inversion of lines ex 1
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_062]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_062]
----
****


.tkzexample 063 inversion of lines ex 2
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_063]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_063]
----
****


.tkzexample 064 inversion of lines ex 3
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_064]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_064]
----
****


.tkzexample 065 inversion of circle and homothety
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_065]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_065]
----
****


.tkzexample 066 inversion of Triangle with respect to the Incircle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_066]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_066]
----
****


.tkzexample 067 inversion: orthogonal circle with inversion circle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_067]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_067]
----
****


.tkzexample 068 inversion negative
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_068]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_068]
----
****


.tkzexample 069 translation of multiple points
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_069]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_069]
----
****


.tkzexample 070 symmetry of multiple points: an oval
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_070]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_070]
----
****


=== \input{TKZdoc-euclide-pointwith.tex}

.tkzexample 071 Option colinear at, simple example
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_071]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_071]
----
****


.tkzexample 072 Option colinear at, complex example
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_072]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_072]
----
****


.tkzexample 073 Option colinear at
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_073]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_073]
----
****


.tkzexample 074 Option colinear at 
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_074]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_074]
----
****


.tkzexample 075 Option orthogonal
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_075]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_075]
----
****


.tkzexample 076 Option orthogonal
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_076]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_076]
----
****


.tkzexample 077 Option orthogonal more complicated example
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_077]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_077]
----
****


.tkzexample 078 Options colinear and orthogonal
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_078]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_078]
----
****


.tkzexample 079 Option orthogonal normed
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_079]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_079]
----
****


.tkzexample 080 Option orthogonal normed and K=2
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_080]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_080]
----
****


.tkzexample 081 Option linear
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_081]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_081]
----
****


.tkzexample 082 Option linear normed
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_082]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_082]
----
****


.tkzexample 083 Coordinate transfer with tkzGetVectxy
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_083]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_083]
----
****


=== \input{TKZdoc-euclide-lines.tex}

.tkzexample 084 With mediator
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_084]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_084]
----
****


.tkzexample 085 An envelope with option mediator
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_085]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_085]
----
****


.tkzexample 086 A parabola with option mediator
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_086]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_086]
----
****


.tkzexample 087 With options bisector and normed
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_087]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_087]
----
****


.tkzexample 088 With option parallel=through
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_088]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_088]
----
****


.tkzexample 089 With option orthogonal and parallel
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_089]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_089]
----
****


.tkzexample 090 With option altitude
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_090]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_090]
----
****


.tkzexample 091 With option euler
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_091]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_091]
----
****


.tkzexample 092 Tangent passing through a point on the circle tangent at
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_092]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_092]
----
****


.tkzexample 093 Choice of contact point with tangents passing through an external point option tangent from
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_093]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_093]
----
****


.tkzexample 094 Example of tangents passing through an external point 
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_094]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_094]
----
****


.tkzexample 095 Example of Andrew Mertz
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_095]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_095]
----
****


.tkzexample 096 Drawing a tangent option tangent from
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_096]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_096]
----
****


=== \input{TKZdoc-euclide-triangles.tex}

.tkzexample 097 Option equilateral
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_097]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_097]
----
****


.tkzexample 098 Option two angles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_098]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_098]
----
****


.tkzexample 099 Option school
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_099]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_099]
----
****


.tkzexample 100 Option pythagore
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_100]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_100]
----
****


.tkzexample 101 Option pythagore and swap
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_101]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_101]
----
****


.tkzexample 102 Option golden
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_102]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_102]
----
****


.tkzexample 103 Option euclid
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_103]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_103]
----
****


.tkzexample 104 Option isosceles right
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_104]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_104]
----
****


.tkzexample 105 Option gold
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{amsmath}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_105]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_105]
----
****


.tkzexample 106 Option medial or centroid
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_106]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_106]
----
****


.tkzexample 107 Option in or incentral
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_107]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_107]
----
****


.tkzexample 108 Option ex or excentral
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_108]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_108]
----
****


.tkzexample 109 Option intouch or contact
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_109]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_109]
----
****


.tkzexample 110 Option extouch
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_110]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_110]
----
****


.tkzexample 111 Option orthic
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_111]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_111]
----
****


.tkzexample 112 Option feuerbach
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_112]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_112]
----
****


.tkzexample 113 Option  tangential
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_113]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_113]
----
****


.tkzexample 114 Option  euler
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_114]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_114]
----
****


.tkzexample 115 Option euler and Option orthic
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_115]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_115]
----
****


.tkzexample 116 Option symmedial
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_116]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_116]
----
****


.tkzexample 117 Modification of the school triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_117]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_117]
----
****


=== \input{TKZdoc-euclide-polygons.tex}

.tkzexample 118 Using tkzDefSquare with two points
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_118]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_118]
----
****


.tkzexample 119 Use of tkzDefSquare to obtain an isosceles right-angled triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_119]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_119]
----
****


.tkzexample 120 Pythagorean Theorem and tkzDefSquare
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_120]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_120]
----
****


.tkzexample 121 Example of a rectangle definition
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_121]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_121]
----
****


.tkzexample 122 Example of a parallelogram definition
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_122]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_122]
----
****


.tkzexample 123 Golden Rectangles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_123]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_123]
----
****


.tkzexample 124 Construction of the golden rectangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_124]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_124]
----
****


.tkzexample 125 Option center
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_125]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_125]
----
****


.tkzexample 126 Option side
****
[tikz,role=right,width=100]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_126]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_126]
----
****


=== \input{TKZdoc-euclide-circles.tex}

.tkzexample 127 Example with option R
****
[tikz,role=right,width=100]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_127]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_127]
----
****


.tkzexample 128 Example with option diameter
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_128]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_128]
----
****


.tkzexample 129 Circles inscribed and circumscribed for a given triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_129]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_129]
----
****


.tkzexample 130 Example with option ex
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_130]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_130]
----
****


.tkzexample 131 Euler's circle for a given triangle with option euler
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_131]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_131]
----
****


.tkzexample 132 Apollonius circles for a given segment option apollonius
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_132]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_132]
----
****


.tkzexample 133 Circles exinscribed to a given triangle option ex
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_133]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_133]
----
****


.tkzexample 134 Spieker circle with option spieker
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_134]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_134]
----
****


.tkzexample 135 Excircles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_135]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_135]
----
****


.tkzexample 136 Orthogonal from
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_136]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_136]
----
****


.tkzexample 137 Orthogonal through
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_137]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_137]
----
****


=== \input{TKZdoc-euclide-circleby.tex}

.tkzexample 138 Translation
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_138]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_138]
----
****


.tkzexample 139 Reflection (orthogonal symmetry)
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_139]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_139]
----
****


.tkzexample 140 Homothety
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_140]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_140]
----
****


.tkzexample 141 Symmetry
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_141]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_141]
----
****


.tkzexample 142 Rotation
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_142]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_142]
----
****


.tkzexample 143 Inversion
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_143]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_143]
----
****


=== \input{TKZdoc-euclide-intersection.tex}

.tkzexample 144 Example of intersection between two straight lines
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_144]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_144]
----
****


.tkzexample 145 test line-circle intersection
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_145]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_145]
----
****


.tkzexample 146 Line-circle intersection
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_146]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_146]
----
****


.tkzexample 147 Line passing through the center option common
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_147]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_147]
----
****


.tkzexample 148 Line-circle intersection with option common
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_148]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_148]
----
****


.tkzexample 149 Line-circle intersection order of points
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_149]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_149]
----
****


.tkzexample 150 Example with foreach
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_150]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_150]
----
****


.tkzexample 151 Line-circle intersection with option near
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_151]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_151]
----
****


.tkzexample 152 More complex example of a line-circle intersection
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_152]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_152]
----
****


.tkzexample 153 Circle defined by a center and a measure, and special cases
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_153]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_153]
----
****


.tkzexample 154 Calculation of radius
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_154]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_154]
----
****


.tkzexample 155 Option \code{with nodes
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_155]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_155]
----
****


.tkzexample 156 test circle-circle intersection
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_156]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_156]
----
****


.tkzexample 157 circle-circle intersection with common point.
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_157]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_157]
----
****


.tkzexample 158 circle-circle intersection order of points.
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_158]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_158]
----
****


.tkzexample 159 Construction of an equilateral triangle.
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_159]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_159]
----
****


.tkzexample 160 Segment trisection
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_160]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_160]
----
****


.tkzexample 161 With the option \code{with nodes
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_161]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_161]
----
****


.tkzexample 162 Mix of intersections
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_162]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_162]
----
****


.tkzexample 163 Altshiller-Court's theorem
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_163]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_163]
----
****


=== \input{TKZdoc-euclide-angles.tex}

.tkzexample 164 Verification of angle measurement
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_164]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_164]
----
****


.tkzexample 165 Determination of the three angles of a triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_165]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_165]
----
****


.tkzexample 166 Angle between two circles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_166]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_166]
----
****


.tkzexample 167 How to use tkzFindSlopeAngle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_167]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_167]
----
****


.tkzexample 168 Use of tkzFindSlopeAngle and tkzGetAngle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_168]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_168]
----
****


.tkzexample 169 Another use of tkzFindSlopeAngle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_169]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_169]
----
****


=== \input{TKZdoc-euclide-rnd.tex}

.tkzexample 170 Random point in a rectangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_170]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_170]
----
****


.tkzexample 171 Random point on a segment or a line
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_171]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_171]
----
****


.tkzexample 172 Random point on a circle or a disk
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_172]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_172]
----
****


== \part{Drawing and Filling}

=== \input{TKZdoc-euclide-drawing.tex}

.tkzexample 173 Example of point drawings
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_173]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_173]
----
****


.tkzexample 174 Example
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_174]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_174]
----
****


.tkzexample 175 Examples with add
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_175]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_175]
----
****


.tkzexample 176 Example with tkzDrawLines
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_176]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_176]
----
****


.tkzexample 177 Example with point references
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_177]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_177]
----
****


.tkzexample 178 Example of extending an segment with option add
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_178]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_178]
----
****


.tkzexample 179 Adding dimensions with option dim new code from Muzimuzhi Z
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_179]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_179]
----
****


.tkzexample 180 Adding dimensions with option dim partI
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_180]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_180]
----
****


.tkzexample 181 Adding dimensions with option dim part II
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_181]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_181]
----
****


.tkzexample 182 Drawing segments tkzDrawSegments
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_182]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_182]
----
****


.tkzexample 183 Place an arrow on segment
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_183]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_183]
----
****


.tkzexample 184 How to draw Altitude 
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_184]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_184]
----
****


.tkzexample 185 tkzDrawPolygon
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_185]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_185]
----
****


.tkzexample 186 Option two angles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_186]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_186]
----
****


.tkzexample 187 Style of line
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_187]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_187]
----
****


.tkzexample 188 Polygonal chain
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_188]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_188]
----
****


.tkzexample 189 The idea is to inscribe two squares in a semi-circle.
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_189]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_189]
----
****


.tkzexample 190 Polygonal chain: index notation
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_190]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_190]
----
****


.tkzexample 191 Circles and styles, draw a circle and color the disc
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_191]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_191]
----
****


.tkzexample 192 Circles defined by a triangle.
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_192]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_192]
----
****


.tkzexample 193 Concentric circles.
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_193]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_193]
----
****


.tkzexample 194 Exinscribed circles.
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_194]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_194]
----
****


.tkzexample 195 Cardioid
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_195]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_195]
----
****


.tkzexample 196 Use of tkzDrawSemiCircle
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_196]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_196]
----
****


.tkzexample 197 Use of tkzDrawSemiCircles : Golden arbelos
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_197]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_197]
----
****


.tkzexample 198 Example of drawing an ellipse
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_198]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_198]
----
****


.tkzexample 199 Option towards
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_199]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_199]
----
****


.tkzexample 200 Option towards
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_200]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_200]
----
****


.tkzexample 201 Option rotate
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_201]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_201]
----
****


.tkzexample 202 Option R
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_202]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_202]
----
****


.tkzexample 203 Option R with nodes
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_203]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_203]
----
****


.tkzexample 204 Option delta
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_204]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_204]
----
****


.tkzexample 205 Option angles: example 1
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_205]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_205]
----
****


.tkzexample 206 Option angles: example 2
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_206]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_206]
----
****


.tkzexample 207 Option reverse: inversion of the arrow
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_207]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_207]
----
****


.tkzexample 208 tkzDrawSector and towards
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_208]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_208]
----
****


.tkzexample 209 tkzDrawSector and rotate
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_209]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_209]
----
****


.tkzexample 210 tkzDrawSector and R
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_210]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_210]
----
****


.tkzexample 211 tkzDrawSector and R with nodes
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_211]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_211]
----
****


.tkzexample 212 tkzDrawSector and R with nodes
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_212]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_212]
----
****


=== \input{TKZdoc-euclide-filling.tex}

.tkzexample 213 Yin and Yang
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_213]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_213]
----
****


.tkzexample 214 From a sangaku
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_214]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_214]
----
****


.tkzexample 215 Clipping and filling part I
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_215]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_215]
----
****


.tkzexample 216 Clipping and filling part II
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_216]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_216]
----
****


.tkzexample 217 Clipping and filling part III
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_217]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_217]
----
****


.tkzexample 218 tkzFillPolygon
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_218]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_218]
----
****


.tkzexample 219 tkzFillSector and towards
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_219]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_219]
----
****


.tkzexample 220 tkzFillSector and rotate
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_220]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_220]
----
****


.tkzexample 221 Example with size
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_221]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_221]
----
****


.tkzexample 222 Changing the order of items
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_222]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_222]
----
****


.tkzexample 223 Changing the order of items} 2
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_223]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_223]
----
****


.tkzexample 224 Multiples angles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_224]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_224]
----
****


=== \input{TKZdoc-euclide-clipping.tex}

.tkzexample 225 tkzClip
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_225]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_225]
----
****


.tkzexample 226 tkzClip and the option space
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_226]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_226]
----
****


.tkzexample 227 Example with tkzShowBB
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_227]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_227]
----
****


.tkzexample 228 Example with tkzClipBB and the bisectors
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_228]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_228]
----
****


.tkzexample 229 tkzClipPolygon
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_229]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_229]
----
****


.tkzexample 230 tkzClipPolygon[out]
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_230]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_230]
----
****


.tkzexample 231 Example: use of \code{Clip} for Sangaku in a square
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_231]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_231]
----
****


.tkzexample 232 Simple clip
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_232]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_232]
----
****


.tkzexample 233 Clip out
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_233]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_233]
----
****


.tkzexample 234 Intersection of disks
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_234]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_234]
----
****


.tkzexample 235 Example 1
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_235]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_235]
----
****


.tkzexample 236 Example 2
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_236]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_236]
----
****


.tkzexample 237 Example about contolling the bouding box
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_237]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_237]
----
****


.tkzexample 238 Example with tkzClipPolygon[out]
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_238]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_238]
----
****


== \part{Marking}

=== \input{TKZdoc-euclide-marking.tex}

.tkzexample 239 Several marks
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_239]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_239]
----
****


.tkzexample 240 Use of mark
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_240]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_240]
----
****


.tkzexample 241 Marks for an isosceles triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_241]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_241]
----
****


.tkzexample 242 Another marking
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_242]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_242]
----
****


.tkzexample 243 Several marks
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_243]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_243]
----
****


.tkzexample 244 Example with mark = x and with mark =||
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_244]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_244]
----
****


.tkzexample 245 Problem to mark a small angle: {Option veclen
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_245]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_245]
----
****


.tkzexample 246 Example of marking a right angle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_246]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_246]
----
****


.tkzexample 247 Example of marking a right angle, german style
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_247]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_247]
----
****


.tkzexample 248 Mix of styles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_248]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_248]
----
****


.tkzexample 249 Full example
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_249]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_249]
----
****


.tkzexample 250 Angle with TikZ
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_250]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_250]
----
****


== \part{Labelling}

=== \input{TKZdoc-euclide-labelling.tex}

.tkzexample 251 Example with tkzLabelPoint
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_251]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_251]
----
****


.tkzexample 252 Label and reference
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_252]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_252]
----
****


.tkzexample 253 Example with tkzLabelPoints
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_253]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_253]
----
****


.tkzexample 254 Label for points with tkzAutoLabelPoints
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_254]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_254]
----
****


.tkzexample 255 First example
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_255]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_255]
----
****


.tkzexample 256 Example : blackboard
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_256]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_256]
----
****


.tkzexample 257 Labels and option : swap
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_257]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_257]
----
****


.tkzexample 258 Labels for an isosceles triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_258]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_258]
----
****


.tkzexample 259 Example with tkzLabelLine
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_259]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_259]
----
****


.tkzexample 260 Example author js bibra stackexchange
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_260]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_260]
----
****


.tkzexample 261 With pos
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_261]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_261]
----
****


.tkzexample 262 pos and tkzLabelAngles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_262]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_262]
----
****


.tkzexample 263 Example
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_263]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_263]
----
****


.tkzexample 264 Label on arc
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz}
include::TKZdoc-euclide-src.adoc[tag=packages]
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_264]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_264]
----
****


== \part{Complements}

=== \input{TKZdoc-euclide-compass.tex}

.tkzexample 265 Option length
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_265]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_265]
----
****


.tkzexample 266 Option delta
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_266]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_266]
----
****


.tkzexample 267 Use tkzCompasss
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_267]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_267]
----
****


=== \input{TKZdoc-euclide-show.tex}

.tkzexample 268 Example of tkzShowLine and parallel
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_268]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_268]
----
****


.tkzexample 269 Example of tkzShowLine and perpendicular
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_269]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_269]
----
****


.tkzexample 270 Example of tkzShowLine and bisector
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_270]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_270]
----
****


.tkzexample 271 Example of tkzShowLine and mediator
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_271]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_271]
----
****


.tkzexample 272 Example of the use of tkzShowTransformation
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_272]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_272]
----
****


.tkzexample 273 Another example of the use of tkzShowTransformation
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_273]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_273]
----
****


=== \input{TKZdoc-euclide-rapporteur.tex}

.tkzexample 274 The circular protractor
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_274]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_274]
----
****


.tkzexample 275 The circular protractor, transparent and returned
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_275]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_275]
----
****


=== \input{TKZdoc-euclide-tools.tex}

.tkzexample 276 Use oftkzDuplicateSegment
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_276]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_276]
----
****


.tkzexample 277 Proportion of gold with tkzDuplicateSegment
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_277]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_277]
----
****


.tkzexample 278 Golden triangle or sublime triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_278]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_278]
----
****


.tkzexample 279 Compass square construction
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_279]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_279]
----
****


.tkzexample 280 Example
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_280]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_280]
----
****


.tkzexample 281 Coordinate transfer with tkzGetPointCoord
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_281]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_281]
----
****


.tkzexample 282 Sum of vectors with tkzGetPointCoord
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_282]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_282]
----
****


.tkzexample 283 Use of tkzSwapPoints
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_283]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_283]
----
****


.tkzexample 284 Simple example
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_284]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_284]
----
****


.tkzexample 285 Cocyclic points
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_285]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_285]
----
****


.tkzexample 286 Power from the radical axis
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_286]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_286]
----
****


.tkzexample 287 Two circles disjointed
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_287]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_287]
----
****


.tkzexample 288 Two intersecting circles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_288]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_288]
----
****


.tkzexample 289 Two externally tangent circles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_289]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_289]
----
****


.tkzexample 290 Two circles tangent internally
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_290]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_290]
----
****


.tkzexample 291 Three circles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_291]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_291]
----
****


.tkzexample 292 Use of tkzIsOrtho and tkzIsLinear
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_292]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_292]
----
****


== \part{Working with style}

=== \input{TKZdoc-euclide-styles.tex}

.tkzexample 293 Global style or local style
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_293]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_293]
----
****


.tkzexample 294 Local style
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_294]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_294]
----
****


.tkzexample 295 Style and scope
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_295]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_295]
----
****


.tkzexample 296 Simple example with tkzSetUpPoint
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_296]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_296]
----
****


.tkzexample 297 Use of tkzSetUpPoint inside a group
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_297]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_297]
----
****


.tkzexample 298 Change line width
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_298]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_298]
----
****


.tkzexample 299 Change style of line
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_299]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_299]
----
****


.tkzexample 300 Example 3: extend lines
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_300]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_300]
----
****


.tkzexample 301 Use of tkzSetUpArc
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_301]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_301]
----
****


.tkzexample 302 Use of tkzSetUpCompass
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_302]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_302]
----
****


.tkzexample 303 Use of tkzSetUpCompass with tkzShowLine
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_303]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_303]
----
****


.tkzexample 304 Use of tkzSetUpLabel
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_304]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_304]
----
****


.tkzexample 305 Use of tkzSetUpStyle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_305]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_305]
----
****


.tkzexample 306 Arrows at endpoints on segment, ray or line
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_306]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_306]
----
****


.tkzexample 307 Arrows at endpoints on segment, ray or line 2
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_307]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_307]
----
****


.tkzexample 308 Arrows at endpoints on segment, ray or line 3
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_308]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_308]
----
****


.tkzexample 309 Arrows at endpoints on segment, ray or line 4
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_309]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_309]
----
****


.tkzexample 310 Arrows at endpoints on segment, ray or line 5
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_310]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_310]
----
****


.tkzexample 311 Arrows at endpoints on segment, ray or line 6
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_311]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_311]
----
****


.tkzexample 312 Arrows at endpoints on segment, ray or line 7
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_312]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_312]
----
****


.tkzexample 313 Scaling an arrow head
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_313]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_313]
----
****


.tkzexample 314 Using vector style
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_314]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_314]
----
****


.tkzexample 315 In a parallelogram
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_315]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_315]
----
****


.tkzexample 316 A line parallel to another one
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_316]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_316]
----
****


.tkzexample 317 Arrow on a circle
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_317]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_317]
----
****


.tkzexample 318 Arrow on each segment with tkz arrows
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_318]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_318]
----
****


.tkzexample 319 Using tkz arrows with a circle
****
[tikz,role=right,width=160]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_319]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_319]
----
****


== \part{Examples}

=== \input{TKZdoc-euclide-others.tex}

.tkzexample 320 Code from Andrew Swan
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_320]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_320]
----
****


.tkzexample 321 Example: Dimitris Kapeta
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_321]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_321]
----
****


.tkzexample 322 Example : John Kitzmiller
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_322]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_322]
----
****


.tkzexample 323 Example 1: from Indonesia
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_323]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_323]
----
****


.tkzexample 324 Example 2: from Indonesia
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_324]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_324]
----
****


.tkzexample 325 Illustration of the Morley theorem by Nicolas Franois
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_325]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_325]
----
****


.tkzexample 326 Gou gu theorem / Pythagorean Theorem by Zhao Shuang
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_326]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_326]
----
****


.tkzexample 327 Reuleaux-Triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_327]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_327]
----
****


=== \input{TKZdoc-euclide-src.tex}

.tkzexample 328 Square root of the integers
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_328]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_328]
----
****


.tkzexample 329 About right triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_329]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_329]
----
****


.tkzexample 330 Archimedes
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_330]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_330]
----
****


.tkzexample 331 Square and rectangle of same area; Golden section
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_331]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_331]
----
****


.tkzexample 332 Steiner Line and Simson Line
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_332]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_332]
----
****


.tkzexample 333 Lune of Hippocrates
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_333]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_333]
----
****


.tkzexample 334 Lunes of Hasan Ibn al-Haytham
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_334]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_334]
----
****


.tkzexample 335 About clipping circles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_335]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_335]
----
****


.tkzexample 336 Revised version of "Tangente"
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_336]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_336]
----
****


.tkzexample 337 "Le Monde" version
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_337]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_337]
----
****


.tkzexample 338 Triangle altitudes
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_338]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_338]
----
****


.tkzexample 339 Altitudes - other construction
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_339]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_339]
----
****


.tkzexample 340 Three circles in an Equilateral Triangle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_340]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_340]
----
****


.tkzexample 341 Law of sines
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_341]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_341]
----
****


.tkzexample 342 Flower of Life
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_342]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_342]
----
****


.tkzexample 343 Pentagon in a circle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_343]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_343]
----
****


.tkzexample 344 Pentagon in a square
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_344]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_344]
----
****


.tkzexample 345 Hexagon Inscribed version 1
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_345]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_345]
----
****


.tkzexample 346 Hexagon Inscribed version 2
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_346]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_346]
----
****


.tkzexample 347 Power of a point with respect to a circle
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_347]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_347]
----
****


.tkzexample 348 Radical axis of two non-concentric circles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_348]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_348]
----
****


.tkzexample 349 External homothetic center
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_349]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_349]
----
****


.tkzexample 350 Tangent lines to two circles
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_350]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_350]
----
****


.tkzexample 351 Tangent lines to two circles with radical axis
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_351]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_351]
----
****


.tkzexample 352 Middle of a segment with a compass
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_352]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_352]
----
****


.tkzexample 353 Definition of a circle Apollonius
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_353]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_353]
----
****


.tkzexample 354 Application of Inversion : Pappus chain
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_354]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_354]
----
****


.tkzexample 355 Book of lemmas proposition 1 Archimedes
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_355]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_355]
----
****


.tkzexample 356 Book of lemmas proposition 6 Archimedes
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_356]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_356]
----
****


.tkzexample 357 "The" Circle of APOLLONIUS
****
[tikz,role=right]
----
\documentclass{standalone}
\usepackage{tikz,tkz-euclide}
include::TKZdoc-euclide-src.adoc[tag=docstyle]
\begin{document}
include::TKZdoc-euclide-src.adoc[tag=ex_357]
\end{document}
----
[source]
----
include::TKZdoc-euclide-src.adoc[tag=ex_357]
----
****

